# Generated by Django 4.2 on 2025-09-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_topic_room_host_massage_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
