# Generated by Django 4.2 on 2025-09-19 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playground', '0003_alter_room_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
    ]
