# Generated by Django 4.2 on 2025-09-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
